project:
  type: book
  output-dir: docs

book:
  title: "Project Management Documentation"
  author: "AIM RSF"
  date: "1/29/2023"
  search: true
  repo-url: https://github.com/aim-rsf/Project-Management-Documentation
  repo-actions: [edit]
  site-url: https://project-management-docs.netlify.app/
  sidebar:
    collapse-level: 3
    pinned: true
  chapters:
    - index.qmd
    - intro.qmd
    - overview.qmd
    - governance.qmd
    - schedule.qmd
    - communication.qmd
    - part: "Events and Activities"
      chapters: 
        - 01-seminars.qmd
        - 02-conference.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    callout-appearance: simple
  pdf:
    documentclass: krantz
    include-in-header: latex/preamble.tex
    include-before-body: latex/before_body.tex
    include-after-body: latex/after_body.tex
    keep-tex: true
    callout-appearance: simple



