---
editor: 
  markdown: 
    wrap: sentence
---

# Events

In summary, this book has no content whatsoever.
We will include all docs.

## Monthly Seminars

Here's a checklist for organizing an online seminar for the "AI for multiple long-term conditions: Research Support Facility" project:

- [ ] Identify a speaker after discussion with the theme leads
- [ ] Determine the seminar objective and target audience.
- [ ] Invite the speaker, using this template.
- [ ] Set a date and time for the seminar that is convenient for the speaker.
- [ ] Identify a chair for the seminar from AIM RSF team.
- [ ] Create a link for the seminar through Zoom
- [ ] Contact the technical team to add the seminar to the official website
- [ ] Promote the seminar in the AIM RSF Slack Workspace and Alan Turing Slack Workspace
- [ ] Send an email to all the AIM consortium to register to the seminar
- [ ] Prepare the seminar agenda and any necessary presentations or materials for the intro.
- [ ] Ensure that all technical requirements are met, including audio and video equipment and internet connectivity by testing 15 mins prior to the seminar.
- [ ] Send out reminders to attendees before the seminar.
- [ ] Set up a Q&A or discussion session during or after the seminar.
- [ ] Follow up with attendees after the seminar to gather feedback and suggestions for improvement.
